# Generated by Django 3.2.8 on 2024-01-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hosts',
            index=models.Index(fields=['host_id'], name='hosts_join2_idx'),
        ),
    ]
