# Generated by Django 3.2.8 on 2024-01-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0002_hosts_hosts_join2_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hosts',
            name='hosts_join1_idx',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='device_group_id',
        ),
        migrations.AddField(
            model_name='hosts',
            name='host_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='zabbix.hostgroups'),
        ),
        migrations.AddIndex(
            model_name='hosts',
            index=models.Index(fields=['host_group_id', 'device_brand', 'device_type'], name='hosts_join1_idx'),
        ),
    ]
