# Generated by Django 3.2.8 on 2024-01-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0003_auto_20240121_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='zabbix.hostgroups'),
        ),
    ]
