# Generated by Django 3.2.8 on 2024-01-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0004_alter_hosts_host_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zabbix.hostgroups'),
        ),
    ]
