# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_auto_20161106_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionprofile',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_content_type', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='userpermissionprofile',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='code name'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='content_type',
        ),
    ]
