# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170108_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionprofile',
            name='object_ids',
        ),
        migrations.AddField(
            model_name='userpermissionprofile',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
