# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0013_auto_20170205_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissionprofileobject',
            unique_together=set([('user_permission_profile', 'content_type', 'object_id')]),
        ),
    ]
