# Generated by Django 3.2.8 on 2021-11-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210130_1435'),
        ('users', '0017_alter_user_type'),
    ]

    operations = [
    ]
