# Generated by Django 3.2.8 on 2021-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_portmanlog_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portmanlog',
            name='exception_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portmanlog',
            name='reseller_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='portmanlog',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
