# Generated by Django 3.2.8 on 2023-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_notificationlog_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap_group_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
