# Generated by Django 3.2.8 on 2023-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_ldap_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('SUPPORT', 'Support'), ('RESELLER', 'Reseller'), ('DIRECTRESELLER', 'DirectReseller')], default='SUPPORT', max_length=256),
        ),
    ]
