# Generated by Django 3.2.8 on 2024-06-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20240606_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='send_type',
            field=models.CharField(blank=True, default='in_app', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
