# Generated by Django 3.2.8 on 2024-07-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0223_city_crm_id'),
        ('users', '0032_auto_20240712_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroupindex',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dslam.city'),
        ),
    ]
