# Generated by Django 3.2.8 on 2025-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
