# Generated by Django 3.2.8 on 2023-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0002_oltcommand_olttypecommand'),
    ]

    operations = [

    ]
