# Generated by Django 3.2.8 on 2023-06-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0217_auto_20230522_1244'),
        ('olt', '0003_auto_20230228_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('olt_number', models.IntegerField(blank=True, default=0, null=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('version', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='new', max_length=256, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_duration', models.IntegerField(blank=True, null=True)),
                ('uptime', models.CharField(blank=True, max_length=256, null=True)),
                ('hostname', models.CharField(blank=True, max_length=256, null=True)),
                ('conn_type', models.CharField(max_length=32)),
                ('get_snmp_community', models.CharField(blank=True, max_length=64, null=True)),
                ('set_snmp_community', models.CharField(blank=True, max_length=64, null=True)),
                ('snmp_port', models.IntegerField(blank=True, null=True)),
                ('snmp_timeout', models.IntegerField(blank=True, default=3, null=True)),
                ('telnet_username', models.CharField(blank=True, max_length=64, null=True)),
                ('telnet_password', models.CharField(blank=True, max_length=64, null=True)),
                ('slot_count', models.IntegerField(blank=True, default=17, null=True)),
                ('port_count', models.IntegerField(blank=True, default=72, null=True)),
                ('availability_start_time', models.DateTimeField(auto_now_add=True)),
                ('down_seconds', models.BigIntegerField(default=0)),
                ('fqdn', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt.olttype')),
                ('telecom_center',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter',
                                   verbose_name='Telecom Center')),
            ],
        ),
        migrations.AddField(
            model_name='olt',
            name='gemport',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='inbound_index',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='outbound_index',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='vlan_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ATBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('label', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('serial', models.CharField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('core_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('max_capacity', models.IntegerField(blank=True, default=4, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('olt_port_number', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('long', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FATType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OLTCabinetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('core_count', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ONT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splitter_leg_number', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=24, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=24, null=True)),
                ('profile', models.CharField(blank=True, max_length=24, null=True)),
                ('owning_status', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('olt_slot_number', models.IntegerField(blank=True, null=True)),
                ('olt_port_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ONTType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('legs_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='olt',
            name='telecom_center',
        ),
        migrations.AddField(
            model_name='olt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=32, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='mg_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='ont_port_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='profile_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='conn_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='olt',
            name='fqdn',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='get_snmp_community',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='hostname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='set_snmp_community',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='telnet_password',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='telnet_username',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='uptime',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='oltcommand',
            name='text',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='olttype',
            name='name',
            field=models.CharField(max_length=24, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.IntegerField(blank=True, null=True)),
                ('cable_meterage', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('long', models.CharField(blank=True, max_length=32, null=True)),
                ('fqdn', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=24, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=256, null=True)),
                ('fiber_number_color', models.CharField(blank=True, max_length=24, null=True)),
                ('user_type', models.CharField(blank=True, max_length=24, null=True)),
                ('atb_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.atbtype')),
                ('cable_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.cabletype')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.ont')),
            ],
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('max_capacity', models.IntegerField(blank=True, default=32, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('space', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('FAT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.fat')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.splitter')),
                ('splitter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.splittertype')),
            ],
        ),
        migrations.AddField(
            model_name='ont',
            name='ont_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.onttype'),
        ),
        migrations.AddField(
            model_name='ont',
            name='splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.splitter'),
        ),
        migrations.CreateModel(
            name='OLTCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('long', models.CharField(blank=True, max_length=32, null=True)),
                ('max_capacity', models.IntegerField(blank=True, default=2, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.city', verbose_name='city')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltcabinettype')),
            ],
        ),
        migrations.AddField(
            model_name='fat',
            name='fat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.fattype'),
        ),
        migrations.AddField(
            model_name='fat',
            name='olt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.olt'),
        ),
        migrations.AddField(
            model_name='fat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.fat'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.oltcabinet'),
        ),
    ]
