# Generated by Django 3.2.8 on 2023-06-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0004_auto_20230614_1614'),
    ]

    operations = [

        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (18, 'Sikas-Complex', 0, '172.24.127.251', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2022-11-11 09:28:05.529033+03:30', 0, 'yaz.yazd.complex-sikas.b.olt.ma5608.01', '2022-11-11 09:28:05.529063+03:30', '2023-01-07 04:59:55.235345+03:30', 1, 10, 500, 500, 0);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (29, 'Ariana_olt', 0, '172.20.133.166', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'PTSsnmpCacti', 'pteSnmpZ', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-05-25 11:12:45.469268+03:30', 0, 'yaz.yazd.complex-ariyana.b.olt.ma5608.01', '2023-05-25 11:12:45.469307+03:30', '2023-05-25 11:21:37.256526+03:30', 1, 10, 10, 10, 3226);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (20, 'Sadoughi', 0, '172.24.120.186', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-01-24 11:52:37.854522+03:30', 0, 'yaz.yazd.complex-sadoughi.b.olt.ma5608.01', '2023-01-24 11:52:37.854571+03:30', '2023-01-24 13:56:46.719946+03:30', 1, 10, 500, 500, 0);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (17, 'Ronika-Complex', 0, '172.19.150.170', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2022-10-29 09:25:17.309641+03:30', 0, 'teh.tehn.complex-ronika.b.olt.ma5608', '2022-10-29 09:25:17.30969+03:30', '2023-05-25 11:21:40.052778+03:30', 1, 10, 10, 10, 3226);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (21, 'Charak', 0, '172.21.171.254', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-02-05 09:11:45.242314+03:30', 0, 'hor.chak.charak.b.olt.ma5608.01', '2023-02-05 09:11:45.242363+03:30', '2023-05-28 09:42:28.361357+03:30', 1, 10, 500, 500, 2705);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (30, 'Charak 2', 0, '172.21.171.246', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpSW', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-05-27 08:35:41.930463+03:30', 0, 'hor.bans.complex-charak.b.olt.ma5608.02', '2023-05-27 08:35:41.930503+03:30', '2023-06-09 18:40:10.450861+03:30', 1, 10, 100, 100, 2705);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (22, 'OLT', 0, '109.125.191.2', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'PTSsnmpCacti', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-02-26 14:22:34.262877+03:30', 0, 'teh.tehn.test', '2023-02-26 14:22:34.262912+03:30', '2023-04-03 11:39:37.608474+03:30', 1, 10, 100, 100, 2371);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (28, 'Fadak-Complex', 0, '172.24.219.250', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-04-04 15:55:18.784898+03:30', 0, 'isf.isfn.complex-fadak.b.olt.ma5608.01', '2023-04-04 15:55:18.784955+03:30', '2023-04-04 16:10:52.504148+03:30', 1, 10, 500, 500, 1214);"),
        migrations.RunSQL(
            "INSERT INTO olt_olt VALUES (19, 'khaneh sefid-Complex', 0, '172.19.172.202', NULL, 't', 'new', NULL, NULL, NULL, NULL, 'telnet', 'pteSnmpZ', 'PTSsnmpCacti', 161, 40, 'admin1', '@secureetp1', 17, 72, '2023-01-10 13:02:30.12708+03:30', 0, 'teh.tehn.complex-khanehsefid.b.olt.ma5608.01', '2023-01-10 13:02:30.127134+03:30', '2023-04-11 14:52:57.742888+03:30', 1, 10, 500, 500, 2236);")

    ]
