# Generated by Django 3.2.8 on 2023-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0005_auto_20230614_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='battery_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='battery_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='cabinet_password',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='cooling_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='key_holder',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='odc_port_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='power_meter_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='power_payment_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='property_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='rectifier_property_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='rectifier_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='olttype',
            name='card_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olttype',
            name='card_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='olttype',
            name='model',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='onttype',
            name='antenna_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onttype',
            name='band_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onttype',
            name='fast_port_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onttype',
            name='gig_port_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
