# Generated by Django 3.2.8 on 2023-07-10 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0006_auto_20230624_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('long', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandholeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('dem_width', models.FloatField(blank=True, null=True)),
                ('dem_height', models.FloatField(blank=True, null=True)),
                ('dem_depth', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('material', models.CharField(blank=True, max_length=16, null=True)),
                ('duct_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True)),
                ('model', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cabletype',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='UsersAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=16)),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField(blank=True, null=True)),
                ('core_number', models.IntegerField(blank=True, null=True)),
                ('loose_color', models.CharField(blank=True, max_length=16, null=True)),
                ('handhole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.handhole')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.jointtype')),
            ],
        ),
        migrations.CreateModel(
            name='HandholeRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_src_type', models.CharField(blank=True, max_length=16, null=True)),
                ('relation_src_id', models.IntegerField(blank=True, null=True)),
                ('extra_cable', models.FloatField(blank=True, null=True)),
                ('handhole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.handhole')),
            ],
        ),
        migrations.AddField(
            model_name='handhole',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.handholetype'),
        ),
    ]
