# Generated by Django 3.2.8 on 2023-07-24 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0007_auto_20230710_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.fat')),
                ('pon_serial_number', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=64)),
                ('customer_username', models.CharField(max_length=32)),
                ('lat', models.CharField(max_length=24)),
                ('lng', models.CharField(max_length=24)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('confirm_ont_id', models.IntegerField(blank=True, null=True)),
                ('ftth_ont_id', models.IntegerField(blank=True, null=True)),
                ('ftth_user_id', models.IntegerField(blank=True, null=True)),
                ('confirmor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('installer', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commands', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
