# Generated by Django 3.2.8 on 2023-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0011_auto_20230801_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
