# Generated by Django 3.2.8 on 2023-08-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0015_remove_reservedports_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontsetup',
            name='reserved_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.reservedports'),
        ),
    ]
