# Generated by Django 3.2.8 on 2023-09-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0019_auto_20230908_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='fat_splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.splitter'),
        ),
        migrations.AddField(
            model_name='fat',
            name='fat_splitter_leg_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fat',
            name='fat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.fattype'),
        ),
        migrations.AlterField(
            model_name='fat',
            name='olt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.olt'),
        ),
        migrations.AlterField(
            model_name='fat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.fat'),
        ),
        migrations.AlterField(
            model_name='olt',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='conn_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='down_seconds',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='olt_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.olttype'),
        ),
    ]
