# Generated by Django 3.2.8 on 2023-10-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0222_auto_20231021_1114'),
        ('olt', '0021_auto_20231004_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='handhole',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dslam.city'),
        ),
    ]
