# Generated by Django 3.2.8 on 2023-12-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0026_microduct_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='microduct',
            old_name='model',
            new_name='usage',
        ),
        migrations.AlterField(
            model_name='microduct',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.microducttype'),
        ),
    ]
