# Generated by Django 3.2.8 on 2024-01-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0028_terminal_cassette_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat',
            name='patch_panel_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminalport'),
        ),
    ]
