# Generated by Django 3.2.8 on 2024-03-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0035_auto_20240304_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdcType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='odc',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='odc',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='odc',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.odctype'),
        ),
    ]
