# Generated by Django 3.2.8 on 2024-04-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0038_oltcard_oltport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitter',
            name='fat_leg_number',
        ),
        migrations.AddField(
            model_name='splitter',
            name='patch_panel_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminalport'),
        ),
    ]
