# Generated by Django 3.2.8 on 2024-04-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0040_alter_oltcard_olt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fat',
            name='olt_port_number',
        ),
        migrations.RemoveField(
            model_name='fat',
            name='olt_slot_number',
        ),
        migrations.RemoveField(
            model_name='fat',
            name='terminal',
        ),
    ]
