# Generated by Django 3.2.8 on 2024-05-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0042_auto_20240427_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='patch_panel_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminalport'),
        ),
    ]
