# Generated by Django 3.2.8 on 2024-05-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0043_reservedports_patch_panel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedports',
            name='leg_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedports',
            name='splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.splitter'),
        ),
    ]
