# Generated by Django 3.2.8 on 2024-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0044_auto_20240501_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handhole',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microduct',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odc',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
