# Generated by Django 3.2.8 on 2024-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0051_alter_terminalport_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltcabinet',
            name='is_odc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ODC',
        ),
        migrations.DeleteModel(
            name='OdcType',
        ),
    ]
