# Generated by Django 3.2.8 on 2024-05-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0053_auto_20240519_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ont',
            name='patch_cord_length',
        ),
        migrations.RemoveField(
            model_name='ont',
            name='patch_cord_type',
        ),
        migrations.RemoveField(
            model_name='ont',
            name='splitter',
        ),
        migrations.RemoveField(
            model_name='ont',
            name='splitter_leg_number',
        ),
        migrations.AddField(
            model_name='user',
            name='patch_cord_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patch_cord_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.patchcordtype'),
        ),
    ]
