# Generated by Django 3.2.8 on 2024-05-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0054_auto_20240520_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='uplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.cable'),
        ),
    ]
