# Generated by Django 3.2.8 on 2024-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0056_auto_20240530_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitter',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fat',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='oltcabinet',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='oltcabinet',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='splitter',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
