# Generated by Django 3.2.8 on 2024-06-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0057_auto_20240615_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fat',
            name='code',
        ),
        migrations.RemoveField(
            model_name='oltcabinet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='splitter',
            name='code',
        ),
    ]
