# Generated by Django 3.2.8 on 2024-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0058_auto_20240623_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='microduct',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
