# Generated by Django 3.2.8 on 2024-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0059_auto_20240702_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltcabinet',
            name='crm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
