# Generated by Django 3.2.8 on 2024-07-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0060_oltcabinet_crm_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='fat',
            index_together={('olt', 'parent', 'is_otb')},
        ),
    ]
