# Generated by Django 3.2.8 on 2024-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0063_alter_oltcabinet_index_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='handhole',
            index=models.Index(fields=['number', 'city'], name='number_city_idx'),
        ),
        migrations.AddIndex(
            model_name='handhole',
            index=models.Index(fields=['city'], name='city_idx'),
        ),
    ]
