# Generated by Django 3.2.8 on 2024-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0067_auto_20240813_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltcabinettype',
            name='is_odc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
