# Generated by Django 3.2.8 on 2024-08-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0068_oltcabinettype_is_odc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalport',
            old_name='input_splitter',
            new_name='in_splitter',
        ),
        migrations.RenameField(
            model_name='terminalport',
            old_name='leg_number',
            new_name='splitter_leg_number',
        ),
    ]
