# Generated by Django 3.2.8 on 2024-10-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0223_city_crm_id'),
        ('olt', '0073_auto_20240930_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('unit_count', models.IntegerField(blank=True, default=1, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dslam.city')),
                ('urban_district', models.PositiveIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=24, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
