# Generated by Django 3.2.8 on 2024-10-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0074_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalport',
            name='olt_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltport'),
        ),
    ]
