# Generated by Django 3.2.8 on 2025-03-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0083_reservedports_ibs_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='install_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fat_install_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oltcabinet',
            name='install_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='install_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
