# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_auto_20170109_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionProfileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_content_type', to='contenttypes.ContentType', verbose_name='content type')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpermissionprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userpermissionprofile',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userpermissionprofileobject',
            name='user_permission_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPermissionProfile'),
        ),
    ]
