# Generated by Django 3.1.2 on 2021-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('SUPPORT', 'Support'), ('RESELLER', 'Reseller')], default='ADMIN', max_length=20),
        ),
    ]
