# Generated by Django 3.2.8 on 2021-12-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_0015_auto_20210130_1435_0017_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortmanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('command', models.CharField(blank=True, max_length=32, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('log_date', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('method_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
