# Generated by Django 3.2.8 on 2021-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_portmanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portmanlog',
            name='log_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
