# Generated by Django 3.2.8 on 2024-06-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_groupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='persian_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='persian_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
