# Generated by Django 3.2.8 on 2024-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_contactgroupindex_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
