# Generated by Django 3.2.8 on 2024-10-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0223_city_crm_id'),
        ('users', '0034_notificationlog_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Read'), (2, 'Write'), (3, 'Read and Write')], null=True)),
                ('scope', models.CharField(blank=True, max_length=16, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dslam.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
