# Generated by Django 3.2.8 on 2025-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_provinceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_validity_date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
