# Generated by Django 3.2.8 on 2025-02-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0223_city_crm_id'),
        ('users', '0036_user_card_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dslam.city'),
        ),
    ]
