# Generated by Django 3.1.2 on 2021-08-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RadioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('router_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiobrand')),
            ],
        ),
        migrations.CreateModel(
            name='RadioGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('router_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiobrand')),
            ],
        ),
        migrations.CreateModel(
            name='RadioCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_command_description', models.CharField(max_length=256)),
                ('router_command_text', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('show_command', models.BooleanField(default=False, verbose_name='Show command in Router table')),
                ('router_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiobrand')),
                ('router_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiotype')),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_interfaceid', models.IntegerField(blank=True, default=0, null=True)),
                ('host_id', models.IntegerField(blank=True, default=0, null=True)),
                ('device_name', models.CharField(blank=True, max_length=256, null=True)),
                ('device_ip', models.CharField(max_length=256)),
                ('device_fqdn', models.CharField(max_length=256)),
                ('SSH_username', models.CharField(max_length=256)),
                ('SSH_password', models.CharField(max_length=256)),
                ('SSH_port', models.IntegerField(blank=True, default=0, null=True)),
                ('SSH_timeout', models.IntegerField(blank=True, default=0, null=True)),
                ('radio_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiobrand')),
                ('radio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiotype')),
            ],
        ),
    ]
