# Generated by Django 3.1.2 on 2021-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiocommand',
            old_name='router_brand',
            new_name='radio_brand',
        ),
        migrations.RenameField(
            model_name='radiocommand',
            old_name='router_command_description',
            new_name='radio_command_description',
        ),
        migrations.RenameField(
            model_name='radiocommand',
            old_name='router_command_text',
            new_name='radio_command_text',
        ),
        migrations.RenameField(
            model_name='radiocommand',
            old_name='router_type',
            new_name='radio_type',
        ),
        migrations.RenameField(
            model_name='radiogroup',
            old_name='router_brand',
            new_name='radio_brand',
        ),
        migrations.RenameField(
            model_name='radiotype',
            old_name='router_brand',
            new_name='radio_brand',
        ),
        migrations.AlterField(
            model_name='radiocommand',
            name='show_command',
            field=models.BooleanField(default=False, verbose_name='Show command in radio table'),
        ),
    ]
