# Generated by Django 3.1.2 on 2021-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20210829_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='Latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='Longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
