from rest_framework import permissions

BASIC = 'BASIC'
ADMIN = 'ADMIN'
SUPPORT = 'SUPPORT'
SUPPORT_ADMIN = 'SUPPORT_ADMIN'
RESELLER = 'RESELLER'
SUPERVISOR = 'SUPERVISOR'
DIRECTRESELLER = 'DIRECTRESELLER'
FTTH_ADMIN = 'FTTH_ADMIN'
FTTH_OPERATOR = 'FTTH_OPERATOR'
FTTH_SUPPORT = 'FTTH_SUPPORT'
FTTH_RESELLER = 'FTTH_RESELLER'
FTTH_INSTALLER = 'FTTH_INSTALLER'
FTTH_CABLER = 'FTTH_CABLER'
FTTH_TECH_AGENT = 'FTTH_TECH_AGENT'
CLOUD_ADMIN = 'CLOUD_ADMIN'
CLOUD_VIEW = 'CLOUD_VIEW'
TECHNICAL_PROFILE_ADMIN = 'TECHNICAL_PROFILE_ADMIN'
FTTH_WEB_SERVICE = 'FTTH_WEB_SERVICE'
FILE_MANAGER_ADMIN = 'FILE_MANAGER_ADMIN'
FILE_MANAGER_VIEWER = 'FILE_MANAGER_VIEWER'
NGN_ADMIN = 'NGN_ADMIN'
INFRA_ADMIN = 'INFRA_ADMIN'
LTE_MAP_ADMIN = 'LTE_MAP_ADMIN'
CONTRACTOR = 'CONTRACTOR'
NOTE_ADMIN = 'NOTE_ADMIN'
NOTIFICATION_ADMIN = 'NOTIFICATION_ADMIN'
KNOWLEDGE_GRAPH_ADMIN = 'KNOWLEDGE_GRAPH_ADMIN'


def user_has_ldap_groups(user, groups):
    return user.ldap_groups_contains(groups);


def user_type_is(user, type):
    return user and user.type_contains(type)


def user_type_is_admin(user):
    return user_type_is(user, ADMIN)


def user_type_is_support(user):
    return user_type_is(user, SUPPORT)
