# Generated by Django 3.2.8 on 2023-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20210908_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='last_backup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
