# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('dslam_type', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default=b'ready', max_length=256, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('conn_type', models.CharField(max_length=32)),
                ('snmp_community', models.CharField(blank=True, max_length=64, null=True)),
                ('snmp_port', models.IntegerField(blank=True, null=True)),
                ('snmp_timeout', models.IntegerField(blank=True, default=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSLAMPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port_index', models.CharField(max_length=256)),
                ('port_name', models.CharField(max_length=256)),
                ('admin_status', models.CharField(blank=True, max_length=64, null=True)),
                ('oper_status', models.CharField(blank=True, max_length=64, null=True)),
                ('line_profile', models.CharField(blank=True, max_length=256, null=True)),
                ('upstream_snr', models.IntegerField(blank=True, null=True)),
                ('downstream_snr', models.IntegerField(blank=True, null=True)),
                ('upstream_attenuation', models.IntegerField(blank=True, null=True)),
                ('downstream_attenuation', models.IntegerField(blank=True, null=True)),
                ('upstream_attainable_rate', models.IntegerField(blank=True, null=True)),
                ('downstream_attainable_rate', models.IntegerField(blank=True, null=True)),
                ('upstream_tx_rate', models.IntegerField(blank=True, null=True)),
                ('downstream_tx_rate', models.IntegerField(blank=True, null=True)),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
    ]
