# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMPortSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslam_id', models.IntegerField(blank=True, null=True)),
                ('port_id', models.IntegerField(blank=True, null=True)),
                ('snp_date', models.DateTimeField(auto_now_add=True)),
                ('upstream_snr', models.IntegerField(blank=True, null=True)),
                ('downstream_snr', models.IntegerField(blank=True, null=True)),
                ('upstream_attenuation', models.IntegerField(blank=True, null=True)),
                ('downstream_attenuation', models.IntegerField(blank=True, null=True)),
                ('upstream_attainable_rate', models.IntegerField(blank=True, null=True)),
                ('downstream_attainable_rate', models.IntegerField(blank=True, null=True)),
                ('upstream_tx_rate', models.IntegerField(blank=True, null=True)),
                ('downstream_tx_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
