# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0003_auto_20160105_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='status',
            field=models.CharField(blank=True, default=b'new', max_length=256, null=True),
        ),
    ]
