# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0005_dslam_last_sync_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.City')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('family', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=11)),
                ('national_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.CharField(max_length=256)),
                ('port_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'DISABLE', b'Disable'), (b'ENABLE', b'Enable')], max_length=100)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Port')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Reseller')),
            ],
        ),
        migrations.CreateModel(
            name='TelecomCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.City')),
            ],
        ),
        migrations.AddField(
            model_name='customerreseller',
            name='reseller_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.ResellerPort'),
        ),
    ]
