# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0006_auto_20160625_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='telecom_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter', verbose_name=b'Telecom Center'),
            preserve_default=False,
        ),
    ]
