# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0009_auto_20160629_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='telecom_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter', verbose_name=b'Telecom Center'),
        ),
    ]
