# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0014_auto_20160710_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='dslam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAMType'),
            preserve_default=False,
        ),
    ]
