# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0014_reseller_admin'),
        ('dslam', '0015_dslam_dslam_type'),
    ]

    operations = [
    ]
