# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0020_customerport_dslam'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerport',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='national_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='tel',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
