# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0026_dslamport_line_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamport',
            name='line_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.LineProfile'),
        ),
    ]
