# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0032_dslam_slot_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslam',
            name='slot_numbers',
        ),
    ]
