# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0037_auto_20160815_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamstatus',
            name='uptime',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dslamstatussnapshot',
            name='uptime',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
