# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0039_auto_20160817_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='prefix_bukht_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telecomcenter',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
