# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0046_auto_20160821_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'dslam_connection_error', b'DSLAM Connection Error')], default=b'dslam_connection_error', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
        migrations.CreateModel(
            name='DSLAMPortEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('port_number', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[(b'no_such_object', b'No Such Object')], default=b'no_such_object', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
    ]
