# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0057_auto_20160917_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dslamicmp',
            old_name='avg_ping',
            new_name='avgping',
        ),
        migrations.RenameField(
            model_name='dslamicmp',
            old_name='max_ping',
            new_name='maxping',
        ),
        migrations.RenameField(
            model_name='dslamicmp',
            old_name='min_ping',
            new_name='minping',
        ),
        migrations.RenameField(
            model_name='dslamicmpsnapshot',
            old_name='avg_ping',
            new_name='avgping',
        ),
        migrations.RenameField(
            model_name='dslamicmpsnapshot',
            old_name='max_ping',
            new_name='maxping',
        ),
        migrations.RenameField(
            model_name='dslamicmpsnapshot',
            old_name='min_ping',
            new_name='minping',
        ),
    ]
