# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0061_auto_20160921_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamport',
            name='downstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dslamport',
            name='downstream_snr_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dslamport',
            name='upstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dslamport',
            name='upstream_snr_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dslamportsnapshot',
            name='downstream_attenuation_flag',
            field=models.CharField(choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], default=b'good', max_length=100),
        ),
        migrations.AddField(
            model_name='dslamportsnapshot',
            name='downstream_snr_flag',
            field=models.CharField(choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], default=b'good', max_length=100),
        ),
        migrations.AddField(
            model_name='dslamportsnapshot',
            name='upstream_attenuation_flag',
            field=models.CharField(choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], default=b'good', max_length=100),
        ),
        migrations.AddField(
            model_name='dslamportsnapshot',
            name='upstream_snr_flag',
            field=models.CharField(choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], default=b'good', max_length=100),
        ),
    ]
