# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0064_auto_20160927_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='card_count',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
        migrations.AddField(
            model_name='dslam',
            name='dslam_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dslam',
            name='port_count',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
