# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0065_auto_20161001_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDFDSLAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecom_center_id', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('connection_number', models.IntegerField()),
                ('dslam_id', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('port', models.IntegerField()),
                ('identifier_key', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[(b'free', b'Free'), (b'busy', b'Busy'), (b'disable', b'Disable'), (b'vpn', b'VPN'), (b'wasted', b'Wasted'), (b'delegate', b'Delegate')], default=b'disable', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bukht',
            name='bukht_type',
        ),
        migrations.RemoveField(
            model_name='bukht',
            name='telecom_center',
        ),
        migrations.RemoveField(
            model_name='bukhtport',
            name='bukht',
        ),
        migrations.RemoveField(
            model_name='bukhtportreseller',
            name='bukht_port',
        ),
        migrations.RemoveField(
            model_name='bukhtportreseller',
            name='reseller',
        ),
        migrations.AlterModelOptions(
            name='telecomcentermdf',
            options={'ordering': ('telecom_center', 'row_number', 'floor_count', 'connection_count')},
        ),
        migrations.RenameField(
            model_name='dslam',
            old_name='card_count',
            new_name='slot_count',
        ),
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='connection_number',
            new_name='connection_count',
        ),
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='floor_number',
            new_name='floor_count',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='port_number',
            new_name='port_count',
        ),
        migrations.DeleteModel(
            name='Bukht',
        ),
        migrations.DeleteModel(
            name='BukhtPort',
        ),
        migrations.DeleteModel(
            name='BukhtPortReseller',
        ),
        migrations.DeleteModel(
            name='BukhtType',
        ),
    ]
