# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0077_auto_20161017_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslamportsnapshot',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='dslamport',
            name='mac_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
