# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 09:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0078_auto_20161019_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='uptime',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=256, null=True),
        ),
    ]
