# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0079_auto_20161024_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='uptime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
