# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0080_auto_20161024_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcenter',
            name='prefix_bukht_name',
            field=models.CharField(max_length=4),
        ),
    ]
