# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0083_auto_20161030_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamportvlan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-09-15 01:42:25.231635-04'),
            preserve_default=False,
        ),
    ]
