# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0086_auto_20161101_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerport',
            name='telecom_center_id',
            field=models.IntegerField(db_index=True, default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resellerport',
            name='telecom_center_id',
            field=models.IntegerField(db_index=True, default=6),
            preserve_default=False,
        ),
    ]
