# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0089_auto_20161105_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerport',
            old_name='user_name',
            new_name='username',
        ),
    ]
