# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 07:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0090_auto_20161105_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMBulkCommandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('dslam_succes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dslam_error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('commands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('result_file', models.FileField(upload_to=b'bulk_command_result/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
