# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0092_command_show_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
