# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0101_auto_20161204_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_tx_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_tx_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
