# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0102_auto_20161204_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dslambulkcommandresult',
            old_name='dslam_succes',
            new_name='dslam_success',
        ),
    ]
