# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0104_auto_20161212_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcentermdf',
            name='floor_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telecomcentermdfconfig',
            name='counting_status_port',
            field=models.CharField(choices=[(b'ODD', b'odd'), (b'EVEN', b'even'), (b'STANDARD', b'standard')], default=b'STANDARD', max_length=8),
        ),
        migrations.AddField(
            model_name='telecomcentermdfconfig',
            name='start_of_port',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='telecomcentermdfconfig',
            name='telecom_center_mdf',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenterMDF'),
            preserve_default=False,
        ),
    ]
