# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0105_auto_20161212_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslambulkcommandresult',
            name='dslam_error',
        ),
        migrations.RemoveField(
            model_name='dslambulkcommandresult',
            name='dslam_success',
        ),
        migrations.AddField(
            model_name='dslambulkcommandresult',
            name='error_file',
            field=models.FileField(default='', upload_to=b'bulk_command_result/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dslambulkcommandresult',
            name='success_file',
            field=models.FileField(default='', upload_to=b'bulk_command_result/'),
            preserve_default=False,
        ),
    ]
