# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0108_auto_20161221_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='template_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
