# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0111_auto_20170101_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[(b'dslam', b'dslam'), (b'slot', b'slot'), (b'port', b'port')], default=b'dslamport', max_length=100),
        ),
    ]
