# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0112_auto_20170108_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_attainable_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_attenuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_tx_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='port_index',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='port_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_attainable_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_attenuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_tx_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_attainable_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_attenuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_tx_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_attainable_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_attenuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_tx_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
