# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0114_dslamport_selt_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='availability_start_time',
            field=models.DateTimeField(auto_now_add=True, default='2017-01-22 14:02:07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dslam',
            name='down_seconds',
            field=models.FloatField(default=0),
        ),
    ]
