# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0119_dslamboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamboard',
            name='temperature',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
