# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0124_auto_20170131_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dslamportvlan',
            unique_together=set([('port', 'vlan')]),
        ),
    ]
