# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0125_auto_20170131_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcentermdfconfig',
            name='status_of_port',
            field=models.CharField(choices=[(b'ODD', b'odd'), (b'EVEN', b'even'), (b'STANDARD', b'standard')], default=b'DISABLE', max_length=8),
        ),
        migrations.AlterField(
            model_name='mdfdslam',
            name='status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'WASTED', b'Wasted'), (b'DELEGATE', b'Delegate')], default=b'disable', max_length=50),
        ),
    ]
