# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0126_auto_20170220_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcentermdfconfig',
            name='status_of_port',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'WASTED', b'Wasted'), (b'DELEGATE', b'Delegate')], default=b'DISABLE', max_length=8),
        ),
    ]
