# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0127_auto_20170220_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='mdf_row_orientation',
            field=models.CharField(choices=[(b'HORIZONTAL', b'Horizontal'), (b'VERTICAL', b'Vertical')], default=b'Vertical', max_length=10),
        ),
    ]
