# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0128_telecomcenter_mdf_row_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMPortWested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslam_id', models.IntegerField()),
                ('port_number', models.IntegerField()),
                ('slot_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DSLAMWastedConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslam_id', models.IntegerField()),
                ('slot_number_from', models.IntegerField()),
                ('slot_number_to', models.IntegerField()),
                ('port_number_from', models.IntegerField()),
                ('port_number_to', models.IntegerField()),
            ],
        ),
    ]
