# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0129_dslamportwested_dslamwastedconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamportwested',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-09-15 10:21:27.80728+04:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dslamwastedconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-09-15 10:21:27.80728+04:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dslamwastedconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='dslamportwested',
            unique_together=set([('dslam_id', 'port_number', 'slot_number')]),
        ),
    ]
