# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0133_auto_20170301_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerport',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customerport',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
