# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0138_auto_20170305_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineprofile',
            old_name='ds_max_rate',
            new_name='ds_snr_margin',
        ),
        migrations.RenameField(
            model_name='lineprofile',
            old_name='us_max_rate',
            new_name='max_ds_interleaved',
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='channel_mode',
            field=models.CharField(blank=True, choices=[(b'adsl', b'adsl'), (b'adsl2+', b'adsl2+')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='ds_transmit_rate_adaptation',
            field=models.CharField(blank=True, choices=[(b'fixed', b'fixed'), (b'startup', b'startup'), (b'runtime', b'runtime')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='max_ds_snr_margin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='max_ds_transmit_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='max_us_interleaved',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='max_us_snr_margin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='max_us_transmit_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='min_ds_snr_margin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='min_ds_transmit_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='min_us_snr_margin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='min_us_transmit_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='us_snr_margin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='template_type',
            field=models.CharField(blank=True, choices=[(b'adsl', b'adsl'), (b'adsl2+', b'adsl2+')], max_length=256, null=True),
        ),
    ]
