# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0149_auto_20170314_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecomcentermdf',
            options={'ordering': ('telecom_center', 'row_number', 'floor_start', 'connection_count')},
        ),
    ]
