# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0151_auto_20170314_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfdslam',
            name='dslam_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mdfdslam',
            name='port_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mdfdslam',
            name='slot_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
