# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0152_auto_20170314_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecomcentermdf',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='telecomcentermdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-02-26 13:22:01.771404+03:30'),
            preserve_default=False,
        ),
    ]
