# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0155_auto_20170405_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='version',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
