# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0156_dslam_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamportfaulty',
            name='dslam_faulty_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAMFaultyConfig'),
            preserve_default=False,
        ),
    ]
