# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 11:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0158_auto_20170424_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslambulkcommandresult',
            name='commands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), size=None),
        ),
    ]
