# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0159_auto_20170501_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='fqdn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
