# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0163_auto_20170507_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='english_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
