# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0166_auto_20170524_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='telecom_center',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter', verbose_name=b'Telecom Center'),
            preserve_default=False,
        ),
    ]
