# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0169_auto_20170607_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamcommand',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='portcommand',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
