# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0170_auto_20170607_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfdslam',
            name='status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'FAULTY', b'Faulty'), (b'RESELLER', b'Reseller')], default=b'disable', max_length=50),
        ),
    ]
