# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0174_auto_20170607_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamcart',
            name='telecom_center',
            field=models.ForeignKey(default=89015, on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter'),
            preserve_default=False,
        ),
    ]
