# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0175_dslamcart_telecom_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcentermdf',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.Reseller'),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='firstname',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.City'),
        ),
    ]
