# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0176_auto_20170617_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='vci',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseller',
            name='vpi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mdfdslam',
            name='identifier_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set([('vlan_id', 'vlan_name')]),
        ),
    ]
