# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0177_auto_20180624_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerport',
            name='dslam_fqdn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='resellerport',
            name='dslam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resellerport',
            name='dslam_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resellerport',
            name='dslam_slot',
            field=models.IntegerField(null=True),
        ),
    ]
