# Generated by Django 3.1.2 on 2020-12-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0178_auto_20180630_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='command',
            name='text',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[('dslam', 'dslam'), ('slot', 'slot'), ('port', 'port')], default='dslamport', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslam',
            name='access_name',
            field=models.CharField(blank=True, default='new', max_length=256, null=True, verbose_name='Access Name (vendor: FiberHome)'),
        ),
        migrations.AlterField(
            model_name='dslam',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dslam',
            name='telecom_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter', verbose_name='Telecom Center'),
        ),
        migrations.AlterField(
            model_name='dslambulkcommandresult',
            name='error_file',
            field=models.FileField(upload_to='bulk_command_result/'),
        ),
        migrations.AlterField(
            model_name='dslambulkcommandresult',
            name='result_file',
            field=models.FileField(upload_to='bulk_command_result/'),
        ),
        migrations.AlterField(
            model_name='dslambulkcommandresult',
            name='success_file',
            field=models.FileField(upload_to='bulk_command_result/'),
        ),
        migrations.AlterField(
            model_name='dslamevent',
            name='flag',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='error', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamevent',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'UnRead'), ('resolve', 'Resolve')], default='unread', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamevent',
            name='type',
            field=models.CharField(choices=[('dslam_connection_error', 'DSLAM Connection Error'), ('get_dslam_sysUpTime_error', 'Get DSLAM Uptime Error'), ('get_dslam_temperature_error', 'Get DSLAM Temperature Error'), ('dslam_ping_error', 'DSLAM Ping Error'), ('dslam_trace_route_error', 'DSLAM Trace Route Error')], default='dslam_connection_error', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_snr_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'fair'), ('bad', 'Bad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_snr_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'fair'), ('bad', 'Bad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportevent',
            name='flag',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='error', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamportevent',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'UnRead'), ('resolve', 'Resolve')], default='unread', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamportevent',
            name='type',
            field=models.CharField(choices=[('no_such_object', 'No Such Object')], default='no_such_object', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('poor', 'Poor'), ('bad', 'Bad')], default='good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_snr_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'fair'), ('bad', 'Bad')], default='good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('poor', 'Poor'), ('bad', 'Bad')], default='good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_snr_flag',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'fair'), ('bad', 'Bad')], default='good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamtype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mdfdslam',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy'), ('DISABLE', 'Disable'), ('VPN', 'VPN'), ('FAULTY', 'Faulty'), ('RESELLER', 'Reseller')], default='FREE', max_length=50),
        ),
        migrations.AlterField(
            model_name='resellerport',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'Disable'), ('ENABLE', 'Enable')], default='ENABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='telecomcenter',
            name='mdf_row_orientation',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical')], default='Vertical', max_length=10),
        ),
        migrations.AlterField(
            model_name='telecomcentermdf',
            name='connection_counting_status',
            field=models.CharField(choices=[('ODD', 'odd'), ('EVEN', 'even'), ('STANDARD', 'standard')], default='STANDARD', max_length=8),
        ),
        migrations.AlterField(
            model_name='telecomcentermdf',
            name='floor_counting_status',
            field=models.CharField(choices=[('ODD', 'odd'), ('EVEN', 'even'), ('STANDARD', 'standard')], default='STANDARD', max_length=8),
        ),
        migrations.AlterField(
            model_name='telecomcentermdf',
            name='status_of_port',
            field=models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy'), ('DISABLE', 'Disable'), ('VPN', 'VPN'), ('FAULTY', 'Faulty'), ('RESELLER', 'Reseller')], default='FREE', max_length=8),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.question')),
            ],
        ),
    ]
