# Generated by Django 3.1.2 on 2020-12-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0180_auto_20201206_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='dslamboard',
            name='temperature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamcommand',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamstatus',
            name='line_card_temp',
            field=models.JSONField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='dslamstatussnapshot',
            name='line_card_temp',
            field=models.JSONField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='portcommand',
            name='card_ports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portcommand',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentlinksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.city')),
                ('telecom_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter')),
                ('telecom_center_contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcontracttype')),
            ],
        ),
    ]
