# Generated by Django 3.1.2 on 2020-12-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0184_equipmentcategory_equipmentlinksinfo_telecomcontracttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='telecom_center',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='telecom_center_contract_type',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
        migrations.DeleteModel(
            name='EquipmentlinksInfo',
        ),
        migrations.DeleteModel(
            name='TelecomContractType',
        ),
    ]
