# Generated by Django 3.1.2 on 2020-12-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0192_auto_20201207_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CraPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_price', models.IntegerField(blank=True, default=0, null=True)),
                ('non_interurban_infrastructure_price', models.IntegerField(blank=True, default=0, null=True)),
                ('non_urban_infrastructure_price', models.IntegerField(blank=True, default=0, null=True)),
                ('Capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.capacitytype')),
            ],
        ),
    ]
