# Generated by Django 3.1.2 on 2021-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0199_rented_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_port',
            name='fqdn',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
