# Generated by Django 3.1.2 on 2021-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0200_rented_port_fqdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_port',
            name='fqdn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
