# Generated by Django 3.2.5 on 2021-09-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0199_rentedport'),
        ('dslam', '0200_rented_port_fqdn'),
    ]

    operations = [
    ]
