# Generated by Django 3.2.5 on 2021-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0203_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=256, null=True)),
                ('city_name', models.CharField(blank=True, max_length=256, null=True)),
                ('telecom_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dslam_number', models.IntegerField(blank=True, max_length=256, null=True)),
                ('card', models.IntegerField(blank=True, max_length=256, null=True)),
                ('port', models.IntegerField(blank=True, max_length=256, null=True)),
                ('telco_row', models.IntegerField(blank=True, max_length=256, null=True)),
                ('telco_column', models.IntegerField(blank=True, max_length=256, null=True)),
                ('telco_connection', models.IntegerField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
