# Generated by Django 3.2.8 on 2021-12-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0209_zabbixhosts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZabbixHosts',
        ),
    ]
