# Generated by Django 3.2.8 on 2023-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0217_auto_20230522_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sharepoint_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
