# Generated by Django 3.2.8 on 2023-09-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0220_alter_dslam_last_backup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='last_backup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
