# Generated by Django 3.2.8 on 2024-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0222_auto_20231021_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='crm_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
