# Generated by Django 3.2.8 on 2023-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0009_ontsetup_equipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='olt_slot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fat',
            name='patch_panel_port',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
