# Generated by Django 3.2.8 on 2023-08-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0012_fat_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterage', models.FloatField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('usage', models.CharField(blank=True, max_length=32, null=True)),
                ('dst_extra_cable', models.FloatField(blank=True, null=True)),
                ('src_extra_cable', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.cabletype')),
            ],
        ),
        migrations.CreateModel(
            name='Microduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('channel_count', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('dst_device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('dst_device_id', models.IntegerField(blank=True, null=True)),
                ('src_device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('src_device_id', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('device_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(max_length=24)),
                ('lng', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_count', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltcabinet')),
            ],
        ),
        migrations.RemoveField(
            model_name='joint',
            name='core_count',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='core_number',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='loose_color',
        ),
        migrations.AddField(
            model_name='joint',
            name='code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='TerminalPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(blank=True, null=True)),
                ('loose_color', models.CharField(blank=True, max_length=32, null=True)),
                ('core_color', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.cable')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='MicroductsCables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loose_color', models.CharField(blank=True, max_length=32, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.cable')),
                ('microduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.microduct')),
            ],
        ),
        migrations.CreateModel(
            name='JointsCables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loose_color', models.CharField(blank=True, max_length=32, null=True)),
                ('core_color', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.cable')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.joint')),
            ],
        ),
        migrations.AddField(
            model_name='fat',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminal'),
        ),
    ]
