# Generated by Django 3.2.8 on 2023-08-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0013_auto_20230821_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_id', models.CharField(blank=True, max_length=16, null=True)),
                ('crm_username', models.CharField(blank=True, max_length=24, null=True)),
                ('status', models.IntegerField(blank=True, db_index=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('lat', models.CharField(max_length=24)),
                ('lng', models.CharField(max_length=24)),
                ('fat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.fat')),
                ('ftth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.user')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('splitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.splitter')),
            ],
        ),
    ]
