# Generated by Django 3.2.8 on 2023-08-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0014_reservedports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedports',
            name='fat',
        ),
    ]
