# Generated by Django 3.2.8 on 2023-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0017_auto_20230829_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
