# Generated by Django 3.2.8 on 2023-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0018_fat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitter',
            name='space',
        ),
        migrations.AddField(
            model_name='reservedports',
            name='duration_days',
            field=models.IntegerField(db_index=True, default=7),
        ),
    ]
