# Generated by Django 3.2.8 on 2023-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0020_auto_20230910_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='pon_serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
