# Generated by Django 3.2.8 on 2023-11-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0024_auto_20231127_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fat',
            old_name='fat_splitter_leg_number',
            new_name='leg_number',
        ),
    ]
