# Generated by Django 3.2.8 on 2023-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0025_rename_fat_splitter_leg_number_fat_leg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='microduct',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
