# Generated by Django 3.2.8 on 2024-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0030_auto_20240130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='last_backup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
