# Generated by Django 3.2.8 on 2024-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0031_olt_last_backup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltcabinet',
            name='is_odc',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
