# Generated by Django 3.2.8 on 2024-03-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0222_auto_20231021_1114'),
        ('olt', '0032_oltcabinet_is_odc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('long', models.CharField(blank=True, max_length=32, null=True)),
                ('max_capacity', models.IntegerField(blank=True, default=2, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.city', verbose_name='city')),
            ],
        ),
    ]
