# Generated by Django 3.2.8 on 2024-03-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0033_odc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oltcabinet',
            name='is_odc',
        ),
        migrations.RemoveField(
            model_name='oltcabinet',
            name='odc_port_count',
        ),
    ]
