# Generated by Django 3.2.8 on 2024-03-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('olt', '0034_auto_20240304_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='terminal',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
