# Generated by Django 3.2.8 on 2024-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0036_auto_20240306_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='is_otb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
