# Generated by Django 3.2.8 on 2024-04-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0037_fat_is_otb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OltCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('ports_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltcabinet')),
            ],
        ),
        migrations.CreateModel(
            name='OltPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltcard')),
                ('patch_panel_port', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.terminalport')),
            ],
        ),
    ]
