# Generated by Django 3.2.8 on 2024-04-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0039_auto_20240421_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltcard',
            name='olt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olt.olt'),
        ),
    ]
