# Generated by Django 3.2.8 on 2024-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0045_auto_20240505_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ont',
            name='owning_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='reservedports',
            name='postal_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='postal_code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
