# Generated by Django 3.2.8 on 2024-05-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0046_auto_20240506_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltcabinet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.oltcabinet'),
        ),
    ]
