# Generated by Django 3.2.8 on 2024-05-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0048_cable_previous_cable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='previous_cable',
        ),
        migrations.AddField(
            model_name='terminalport',
            name='out_cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_cable', to='olt.cable'),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='out_core_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='out_loose_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='terminalport',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_cable', to='olt.cable'),
        ),
    ]
