# Generated by Django 3.2.8 on 2024-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0052_auto_20240515_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='urban_district',
        ),
        migrations.AddField(
            model_name='cable',
            name='plan_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fat',
            name='urban_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
