# Generated by Django 3.2.8 on 2024-05-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0055_auto_20240530_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='fat',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='handhole',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='handholetype',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='joint',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='microduct',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='olt',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='oltcard',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='oltport',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='ont',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='splitter',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AddField(
            model_name='user',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
        migrations.AlterField(
            model_name='oltcabinet',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.property'),
        ),
    ]
