# Generated by Django 3.2.8 on 2024-07-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0061_alter_fat_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='fat',
            index_together={('olt', 'parent', 'is_otb'), ('parent', 'is_otb')},
        ),
    ]
