# Generated by Django 3.2.8 on 2024-07-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0223_city_crm_id'),
        ('olt', '0062_alter_fat_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='oltcabinet',
            index_together={('parent', 'is_odc'), ('city', 'parent', 'is_odc')},
        ),
    ]
