# Generated by Django 3.2.8 on 2024-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0065_alter_usersauditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitter',
            name='parent_leg_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
