# Generated by Django 3.2.8 on 2024-08-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0066_splitter_parent_leg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalport',
            name='input_splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.splitter'),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='leg_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
