# Generated by Django 3.2.8 on 2024-09-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('olt', '0069_auto_20240813_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inception_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('point_shoot', models.BooleanField(blank=True, default=False, null=True)),
                ('point_fusion', models.BooleanField(blank=True, default=False, null=True)),
                ('initial_test', models.BooleanField(blank=True, default=False, null=True)),
                ('cabinet_installation', models.BooleanField(blank=True, default=False, null=True)),
                ('cabinet_uplink', models.BooleanField(blank=True, default=False, null=True)),
                ('cabinet_power', models.BooleanField(blank=True, default=False, null=True)),
                ('shoot_uplink', models.BooleanField(blank=True, default=False, null=True)),
                ('sazman_registration', models.TextField(blank=True, null=True)),
                ('inspection_notice', models.TextField(blank=True, null=True)),
                ('inception_status', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
