# Generated by Django 3.2.8 on 2024-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0070_auto_20240903_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inception_status',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='inspection_notice',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='inception_status',
        ),
        migrations.AddField(
            model_name='property',
            name='inspection_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
