# Generated by Django 3.2.8 on 2024-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0071_auto_20240908_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='is_tb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
