# Generated by Django 3.2.8 on 2024-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0072_fat_is_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='sazman_registration',
        ),
        migrations.AddField(
            model_name='inspection',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='site_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
