# Generated by Django 3.2.8 on 2024-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0075_terminalport_olt_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
