# Generated by Django 3.2.8 on 2024-11-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0076_property_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='fat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.fat'),
        ),
    ]
