# Generated by Django 3.2.8 on 2024-12-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0077_reservedports_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='handhole',
            name='is_t',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='handhole',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.handholetype'),
        ),
    ]
