# Generated by Django 3.2.8 on 2024-12-02 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0078_auto_20241201_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.building'),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='installer', to=settings.AUTH_USER_MODEL),
        ),
    ]
