# Generated by Django 3.2.8 on 2024-12-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0079_auto_20241202_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.building'),
        ),
    ]
