# Generated by Django 3.2.8 on 2024-12-20 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0080_fat_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='cabler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabler', to=settings.AUTH_USER_MODEL),
        ),
    ]
