# Generated by Django 3.2.8 on 2025-01-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0081_reservedports_cabler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedports',
            name='ftth_user',
        ),
        migrations.AddField(
            model_name='reservedports',
            name='atb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.atbtype'),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='cable_meterage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='cable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olt.cabletype'),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='fiber_number_color',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='patch_cord_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservedports',
            name='patch_cord_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olt.patchcordtype'),
        ),
    ]
