# Generated by Django 3.2.8 on 2025-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0082_auto_20250106_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='ibs_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
