# Generated by Django 3.2.8 on 2025-03-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olt', '0084_auto_20250309_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedports',
            name='tech_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tech_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
