# Generated by Django 3.2.8 on 2024-03-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappointcomment',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lte.mappoint'),
        ),
    ]
