# Generated by Django 3.2.8 on 2025-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_call_callhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
