# Generated by Django 3.2.8 on 2025-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0004_call_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
