# Generated by Django 3.2.8 on 2025-02-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0005_callhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='need_tracking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='previous_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge_graph.call'),
        ),
        migrations.AddField(
            model_name='node',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
