# Generated by Django 3.2.8 on 2024-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
