# Generated by Django 3.2.8 on 2024-07-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_configrequest_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrequest',
            name='is_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
