# Generated by Django 3.2.8 on 2024-06-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filemanager', '0003_file_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
    ]
