# Generated by Django 3.2.8 on 2025-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shp_id', models.PositiveIntegerField(blank=True, null=True)),
                ('shp_city_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name_display', models.CharField(blank=True, max_length=128, null=True)),
                ('name_config', models.CharField(blank=True, max_length=128, null=True)),
                ('gps_latitude', models.CharField(blank=True, max_length=24, null=True)),
                ('gps_longitude', models.CharField(blank=True, max_length=24, null=True)),
                ('gps_altitude', models.IntegerField(blank=True, null=True)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=24, null=True)),
                ('building_height', models.PositiveIntegerField(blank=True, null=True)),
                ('tower_type', models.CharField(blank=True, max_length=64, null=True)),
                ('tower_height', models.PositiveIntegerField(blank=True, null=True)),
                ('covered_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('skynode_note', models.TextField(blank=True, null=True)),
                ('has_problems', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
