# Generated by Django 3.1.2 on 2021-02-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210202_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.contacttype'),
            preserve_default=False,
        ),
    ]
