# Generated by Django 3.1.2 on 2021-02-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0198_location_locationtype_router_routerbrand_routertype_switch_switchbrand_switchtype'),
        ('contact', '0004_auto_20210206_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rastin_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ranjePhoneNumber', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('slot_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('port_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('telco_row', models.IntegerField(blank=True, db_index=True, null=True)),
                ('port_Column', models.IntegerField(blank=True, db_index=True, null=True)),
                ('telco_connection', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fqdn', models.CharField(max_length=256)),
                ('order_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('order_dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.dslam')),
            ],
        ),
    ]
