# Generated by Django 3.1.2 on 2021-02-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_order_order_dslam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_contact',
            new_name='order_contact_id',
        ),
    ]
