# Generated by Django 3.1.2 on 2021-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20210206_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_contact_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
