# Generated by Django 3.1.2 on 2021-02-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210206_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='port_Column',
            new_name='telco_column',
        ),
    ]
