# Generated by Django 3.2.5 on 2021-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210207_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fqdn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ranjePhoneNumber',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
