# Generated by Django 3.2.8 on 2021-11-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20211106_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='PortmapStates',
        ),
    ]
