# Generated by Django 3.2.8 on 2021-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_rename_portmapstates_portmapstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('provinceName', models.CharField(blank=True, max_length=256, null=True)),
                ('externalId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('shaskam_Url', models.CharField(blank=True, max_length=256, null=True)),
                ('shaskam_Username', models.CharField(blank=True, max_length=256, null=True)),
                ('Shaskam_Password', models.CharField(blank=True, max_length=256, null=True)),
                ('Shaskam_CompanyId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('TCIId', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
