# Generated by Django 3.2.8 on 2021-11-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cityName', models.CharField(blank=True, max_length=256, null=True)),
                ('provinceId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('externalId', models.CharField(blank=True, max_length=256, null=True)),
                ('areaCode', models.CharField(blank=True, max_length=256, null=True)),
                ('shaskam_CityId', models.CharField(blank=True, max_length=256, null=True)),
                ('TCIId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.province')),
            ],
        ),
    ]
