# Generated by Django 3.2.8 on 2021-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_alter_telecommunicationcenters_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecommunicationcenters',
            name='telecomCenterId',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
