# Generated by Django 3.2.8 on 2021-11-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_delete_telecommunicationcenters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecommunicationCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecomCenterId', models.IntegerField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.IntegerField(blank=True, db_index=True, null=True)),
                ('areaId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('externalId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('externalTelcoName', models.CharField(blank=True, max_length=256, null=True)),
                ('activeInBitStream', models.BooleanField()),
                ('CRAId', models.IntegerField(blank=True, max_length=1, null=True)),
                ('TCIId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('centerTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.centertype')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.city')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='telecom',
            field=models.ForeignKey(default=125, on_delete=django.db.models.deletion.CASCADE, to='contact.telecommunicationcenters'),
            preserve_default=False,
        ),
    ]
