# Generated by Django 3.2.8 on 2022-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_order_dslam'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarzaneganProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=250)),
                ('total_traffic', models.IntegerField()),
                ('used_traffic', models.IntegerField()),
                ('remain_traffic', models.IntegerField()),
                ('total_numbers', models.IntegerField()),
                ('used_numbers', models.IntegerField()),
                ('remain_numbers', models.IntegerField()),
                ('total_data_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarzaneganTDLTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_key', models.DateField()),
                ('provider', models.CharField(max_length=32)),
                ('customer_msisdn', models.CharField(max_length=32)),
                ('total_data_volume_income', models.CharField(max_length=32)),
            ],
        ),
    ]
