# Generated by Django 3.2.8 on 2022-01-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_auto_20220115_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farzanegantdlte',
            name='provider',
        ),
        migrations.DeleteModel(
            name='FarzaneganProvider',
        ),
        migrations.DeleteModel(
            name='FarzaneganTDLTE',
        ),
    ]
