# Generated by Django 3.2.8 on 2022-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0039_pishgamannote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishgamannote',
            name='register_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
