# Generated by Django 3.2.8 on 2022-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0043_auto_20220906_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLocationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('action', models.CharField(blank=True, max_length=15, null=True)),
                ('old_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('log_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
