# Generated by Django 3.2.8 on 2023-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0045_technicalprofile_technicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalprofile',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='technicaluser',
            name='type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='technicaluser',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
