# Generated by Django 3.2.8 on 2023-09-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0220_alter_dslam_last_backup_date'),
        ('contact', '0046_auto_20230919_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalprofile',
            name='city',
            field=models.ForeignKey(default=1627, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_id', to='dslam.city'),
        ),
        migrations.AddField(
            model_name='technicalprofile',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='province_id', to='dslam.city'),
        ),
    ]
