# Generated by Django 3.2.8 on 2024-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0047_auto_20230925_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pishgamannote',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
