# Generated by Django 3.2.8 on 2024-01-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0048_pishgamannote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PishgamanNoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=12, null=True)),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
