# Generated by Django 3.2.8 on 2023-06-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sharepoint_id', models.CharField(blank=True, max_length=40, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ERROR', 'error'), ('DONE', 'done')], default='PENDING', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud.configrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='configrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device', to='cloud.device'),
        ),
        migrations.AddField(
            model_name='configrequest',
            name='first_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configrequest',
            name='requester_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configrequest',
            name='second_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
