# Generated by Django 3.1.2 on 2020-12-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('switch', '0002_auto_20201208_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('Switch_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_interfaceid', models.IntegerField(blank=True, default=0, null=True)),
                ('host_id', models.IntegerField(blank=True, default=0, null=True)),
                ('device_name', models.CharField(blank=True, max_length=256, null=True)),
                ('device_ip', models.CharField(max_length=256)),
                ('device_fqdn', models.CharField(max_length=256)),
                ('Switch_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchbrand')),
                ('Switch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchtype')),
            ],
        ),
    ]
