# Generated by Django 3.1.2 on 2021-01-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_switch_switchbrand_switchtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_command_description', models.CharField(max_length=256)),
                ('switch_command_text', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('show_command', models.BooleanField(default=False, verbose_name='Show command in Switch table')),
                ('switch_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchbrand')),
                ('switch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchtype')),
            ],
        ),
    ]
