# Generated by Django 3.1.2 on 2021-05-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_switchcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchcommand',
            name='switch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='switch.switch'),
            preserve_default=False,
        ),
    ]
