# Generated by Django 3.1.2 on 2021-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0008_auto_20210620_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='SSH_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
