# Generated by Django 3.1.2 on 2021-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0009_switch_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='SSH_timeout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
