# Generated by Django 3.1.2 on 2021-08-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0010_switch_ssh_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('router_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switchbrand')),
            ],
        ),
    ]
