# Generated by Django 3.1.2 on 2021-08-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0011_switchgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchgroup',
            old_name='router_brand',
            new_name='switch_brand',
        ),
    ]
