# Generated by Django 3.2.8 on 2024-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0014_alter_switch_host_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='host_id',
            new_name='host',
        ),
    ]
