# Generated by Django 3.2.8 on 2021-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0010_router_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
