# Generated by Django 3.2.8 on 2024-01-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0002_hosts_hosts_join2_idx'),
        ('router', '0012_auto_20240121_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='host_id',
            new_name='host',
        )
    ]
