# Generated by Django 3.2.8 on 2024-05-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
