# Generated by Django 3.2.8 on 2024-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartable', '0007_auto_20240701_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sending_methods',
            field=models.CharField(max_length=20),
        ),
    ]
