# Generated by Django 3.2.8 on 2025-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='chakavak_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
