# Generated by Django 3.1.2 on 2021-01-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_router_routerbrand_routertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_command_description', models.CharField(max_length=256)),
                ('router_command_text', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('show_command', models.BooleanField(default=False, verbose_name='Show command in Router table')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.router')),
                ('router_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.routerbrand')),
                ('router_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.routertype')),
            ],
        ),
    ]
