# Generated by Django 3.1.2 on 2021-01-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_routercommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routercommand',
            name='router',
        ),
    ]
