# Generated by Django 3.1.2 on 2021-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_remove_routercommand_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='SSH_password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='SSH_username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
