# Generated by Django 3.1.2 on 2021-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_auto_20210620_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='SSH_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
