# Generated by Django 3.1.2 on 2021-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0007_router_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='SSH_timeout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
