# Generated by Django 3.1.2 on 2021-02-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dslam', '0198_location_locationtype_router_routerbrand_routertype_switch_switchbrand_switchtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256)),
                ('mobile_phone', models.CharField(max_length=256)),
                ('contact_email', models.CharField(max_length=256)),
                ('contact_telecom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contacttype')),
            ],
        ),
    ]
