# Generated by Django 3.1.2 on 2021-02-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0198_location_locationtype_router_routerbrand_routertype_switch_switchbrand_switchtype'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_telecom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_dslam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dslam.dslam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
