# Generated by Django 3.1.2 on 2021-02-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_dslam',
        ),
        migrations.AddField(
            model_name='contact',
            name='rastin_contact_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
