# Generated by Django 3.1.2 on 2021-02-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_dslam',
        ),
    ]
