# Generated by Django 3.2.8 on 2021-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20211012_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
