# Generated by Django 3.2.8 on 2021-11-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_auto_20211106_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortmapStates',
            new_name='PortmapState',
        ),
    ]
