# Generated by Django 3.2.8 on 2021-11-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_telecommunicationcenters_telecomcenterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecommunicationcenters',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contact.city'),
            preserve_default=False,
        ),
    ]
