# Generated by Django 3.2.8 on 2021-11-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_alter_telecommunicationcenters_activeinbitstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telecom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contact.telecommunicationcenters'),
            preserve_default=False,
        ),
    ]
