# Generated by Django 3.2.8 on 2021-11-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_remove_order_telecom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelecommunicationCenters',
        ),
    ]
