# Generated by Django 3.2.8 on 2021-11-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0208_merge_0201_auto_20210915_1225_0207_testmodel'),
        ('contact', '0030_auto_20211108_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dslam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.dslam'),
        ),
    ]
