# Generated by Django 3.2.8 on 2022-01-15 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_alter_farzaneganprovider_total_data_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='farzaneganprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farzanegantdlte',
            name='provider_number',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farzanegantdlte',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_data', to='contact.farzaneganprovider'),
        ),
    ]
