# Generated by Django 3.2.8 on 2022-01-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0035_auto_20220115_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarzaneganProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FarzaneganTDLTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_key', models.DateField()),
                ('provider_number', models.CharField(max_length=32)),
                ('customer_msisdn', models.CharField(max_length=32)),
                ('total_data_volume_income', models.CharField(max_length=32)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_data', to='contact.farzaneganprovider')),
            ],
        ),
        migrations.CreateModel(
            name='FarzaneganProviderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_traffic', models.IntegerField()),
                ('used_traffic', models.IntegerField()),
                ('remain_traffic', models.IntegerField()),
                ('total_numbers', models.IntegerField()),
                ('used_numbers', models.IntegerField()),
                ('remain_numbers', models.IntegerField()),
                ('total_data_volume', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_total_data', to='contact.farzaneganprovider')),
            ],
        ),
    ]
