# Generated by Django 3.2.8 on 2022-01-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_farzaneganprovider_farzaneganproviderdata_farzanegantdlte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farzaneganproviderdata',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.farzaneganprovider'),
        ),
        migrations.AlterField(
            model_name='farzanegantdlte',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.farzaneganprovider'),
        ),
    ]
