# Generated by Django 3.2.8 on 2022-01-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_auto_20220115_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='farzanegantdlte',
            name='owner_username',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farzaneganproviderdata',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_total_data', to='contact.farzaneganprovider'),
        ),
        migrations.AlterField(
            model_name='farzanegantdlte',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_data', to='contact.farzaneganprovider'),
        ),
    ]
