# Generated by Django 3.2.8 on 2022-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0038_auto_20220116_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PishgamanNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('telecom_center', models.CharField(max_length=250)),
                ('problem_desc', models.TextField()),
                ('register_time', models.DateTimeField()),
                ('username', models.CharField(max_length=120)),
            ],
        ),
    ]
