# Generated by Django 3.2.8 on 2022-08-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0041_auto_20220227_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='telecom',
        ),
    ]
