# Generated by Django 3.2.8 on 2022-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0042_remove_order_telecom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishgamannote',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pishgamannote',
            name='problem_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pishgamannote',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pishgamannote',
            name='telecom_center',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
