# Generated by Django 3.2.8 on 2023-08-28 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0044_datalocationslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=254)),
                ('host_id', models.CharField(max_length=12)),
                ('item', models.CharField(max_length=254)),
                ('item_id', models.CharField(max_length=12)),
                ('service', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('technical_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.technicaluser')),
            ],
        ),
    ]
