# Generated by Django 3.2.8 on 2024-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0049_pishgamannotelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pishgamannote',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pishgamannote',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
