# Generated by Django 3.2.8 on 2024-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartable', '0005_auto_20240609_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
