# Generated by Django 3.1.2 on 2020-12-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchbrand',
            name='Switch_type',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
        migrations.DeleteModel(
            name='SwitchBrand',
        ),
        migrations.DeleteModel(
            name='SwitchType',
        ),
    ]
