# Generated by Django 3.1.2 on 2021-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0005_switchcommand_switch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchcommand',
            old_name='switch_id',
            new_name='switch',
        ),
    ]
