# Generated by Django 3.1.2 on 2021-05-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0006_auto_20210526_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchcommand',
            name='switch',
        ),
    ]
