# Generated by Django 3.1.2 on 2021-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0007_remove_switchcommand_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='SSH_password',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='SSH_username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
