# Generated by Django 3.2.8 on 2024-01-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0002_hosts_hosts_join2_idx'),
        ('switch', '0013_switch_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='host_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='zabbix.hosts'),
        ),
    ]
