# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0004_auto_20160106_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='last_sync_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
