# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0007_dslam_telecom_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=256)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Command')),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
        migrations.RemoveField(
            model_name='port',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='port',
            name='updated_at',
        ),
    ]
