# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0008_auto_20160626_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(db_index=True, max_length=256)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('family', models.CharField(db_index=True, max_length=256)),
                ('user_name', models.CharField(db_index=True, max_length=256)),
                ('tel', models.CharField(db_index=True, max_length=15)),
                ('mobile', models.CharField(db_index=True, max_length=11)),
                ('national_code', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerreseller',
            name='reseller_port',
        ),
        migrations.AddField(
            model_name='reseller',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dslam',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='port_index',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='port_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='dslam_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='port_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='port_index',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='port_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='portcommand',
            name='port_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='resellerport',
            name='port',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='telecomcenter',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='CustomerReseller',
        ),
    ]
