# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0010_auto_20160630_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='dslam',
        ),
        migrations.RenameField(
            model_name='customerport',
            old_name='port',
            new_name='port_name',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
