# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0011_auto_20160701_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='portcommand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-06-30T13:35:32.481330'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portcommand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2016-06-30T13:35:32.481330'),
            preserve_default=False,
        ),
    ]
