# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dslam', '0013_auto_20160709_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
