# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0016_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resellerport',
            old_name='port',
            new_name='port_name',
        ),
        migrations.AddField(
            model_name='resellerport',
            name='dslam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM'),
            preserve_default=False,
        ),
    ]
