# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0017_auto_20160712_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='admin',
        ),
    ]
