# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0018_remove_reseller_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslamportsnapshot',
            name='port_id',
        ),
    ]
