# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0019_remove_dslamportsnapshot_port_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerport',
            name='dslam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM'),
            preserve_default=False,
        ),
    ]
