# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0024_lineprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslamport',
            name='line_profile',
        ),
    ]
