# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0025_remove_dslamport_line_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamport',
            name='line_profile',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, to='dslam.LineProfile'),
            preserve_default=False,
        ),
    ]
