# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0028_auto_20160806_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='resellerport',
            name='status',
            field=models.CharField(choices=[(b'DISABLE', b'Disable'), (b'ENABLE', b'Enable')], default=b'ENABLE', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='resellerport',
            unique_together=set([('reseller', 'dslam', 'port_name')]),
        ),
    ]
