# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0029_auto_20160806_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='dslam',
            field=models.ForeignKey(default=83, on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='lineprofile',
            unique_together=set([('dslam', 'name')]),
        ),
    ]
