# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0031_auto_20160810_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='slot_numbers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
