# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0036_dslamstatussnapshot_line_card_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamstatus',
            name='line_card_temp',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='dslamstatussnapshot',
            name='line_card_temp',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=2048, null=True),
        ),
    ]
