# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0038_auto_20160815_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bukht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('terminal_number', models.IntegerField()),
                ('connection_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BukhtPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslam_number', models.IntegerField(db_index=True)),
                ('slot_number', models.IntegerField(db_index=True)),
                ('port_number', models.IntegerField(db_index=True)),
                ('bukht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Bukht')),
            ],
        ),
        migrations.CreateModel(
            name='BukhtPortReseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukht_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.BukhtPort')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Reseller')),
            ],
        ),
        migrations.CreateModel(
            name='BukhtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='bukht',
            name='bukht_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.BukhtType'),
        ),
        migrations.AddField(
            model_name='bukht',
            name='telecom_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter'),
        ),
    ]
