# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0041_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomCenterMDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('terminal_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('is_new', models.BooleanField(default=True)),
                ('telecom_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.TelecomCenter')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Terminal')),
            ],
        ),
    ]
