# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0042_telecomcentermdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='port_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
