# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0043_terminal_port_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='terminal_number',
            new_name='connection_number',
        ),
        migrations.AlterField(
            model_name='telecomcenter',
            name='prefix_bukht_name',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
