# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0044_auto_20160820_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='row',
            new_name='row_number',
        ),
    ]
