# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0045_auto_20160820_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecomcentermdf',
            options={'ordering': ('telecom_center', 'row_number', 'floor_number', 'connection_number')},
        ),
        migrations.RenameField(
            model_name='dslamtype',
            old_name='text',
            new_name='name',
        ),
    ]
