# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0048_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='text',
            field=models.CharField(max_length=256, unique=True, verbose_name=b'name'),
        ),
    ]
