# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0049_auto_20160827_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMICMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('jitter', models.CharField(blank=True, max_length=10, null=True)),
                ('max_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('min_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('packet_loss', models.CharField(blank=True, max_length=10, null=True)),
                ('received', models.PositiveIntegerField(blank=True, null=True)),
                ('sent', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_route', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
        migrations.CreateModel(
            name='DSLAMICMPSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslam_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('avg_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('jitter', models.CharField(blank=True, max_length=10, null=True)),
                ('max_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('min_ping', models.CharField(blank=True, max_length=10, null=True)),
                ('packet_loss', models.CharField(blank=True, max_length=10, null=True)),
                ('received', models.PositiveIntegerField(blank=True, null=True)),
                ('sent', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_route', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
