# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0050_dslamicmp_dslamicmpsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='ds_max_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='us_max_rate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
