# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0053_dslamlocation_telecomcenterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_lat', models.CharField(max_length=256)),
                ('city_long', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.City', unique=True)),
            ],
        ),
    ]
