# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0054_citylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocation',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dslam.City'),
        ),
    ]
