# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0055_auto_20160917_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.City'),
        ),
    ]
