# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0059_dslamevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamportevent',
            name='status',
            field=models.CharField(choices=[(b'read', b'Read'), (b'unread', b'UnRead'), (b'resolve', b'Resolve')], default=b'unread', max_length=100),
        ),
    ]
