# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0063_dslam_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamport',
            name='uptime',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dslamportsnapshot',
            name='uptime',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
