# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0066_auto_20161001_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telecomcentermdf',
            name='is_new',
        ),
    ]
