# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0067_remove_telecomcentermdf_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerport',
            name='dslam',
        ),
        migrations.RemoveField(
            model_name='customerport',
            name='port_name',
        ),
        migrations.AddField(
            model_name='customerport',
            name='identifier_key',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
