# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0068_auto_20161001_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerport',
            name='identifier_key',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], default=b'good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_attenuation_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'very_good', b'Very Good'), (b'good', b'Good'), (b'poor', b'Poor'), (b'bad', b'Bad')], default=b'good', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resellerport',
            unique_together=set([('identifier_key',)]),
        ),
    ]
