# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0069_auto_20161002_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellerport',
            name='dslam',
        ),
        migrations.RemoveField(
            model_name='resellerport',
            name='port_name',
        ),
    ]
