# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0070_auto_20161002_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_snr_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], default=b'good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_snr_flag',
            field=models.CharField(blank=True, choices=[(b'outstanding', b'Outstanding'), (b'excellent', b'Excellent'), (b'good', b'Good'), (b'fair', b'fair'), (b'bad', b'Bad')], default=b'good', max_length=100, null=True),
        ),
    ]
