# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0071_auto_20161003_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdfdslam',
            old_name='port',
            new_name='port_number',
        ),
        migrations.RenameField(
            model_name='mdfdslam',
            old_name='slot',
            new_name='slot_number',
        ),
        migrations.AlterField(
            model_name='dslam',
            name='port_count',
            field=models.IntegerField(blank=True, default=72, null=True),
        ),
    ]
