# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0073_mdfdslam_telecom_center_mdf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamevent',
            name='type',
            field=models.CharField(choices=[(b'dslam_connection_error', b'DSLAM Connection Error'), (b'get_dslam_sysUpTime_error', b'Get DSLAM Uptime Error'), (b'get_dslam_temperature_error', b'Get DSLAM Temperature Error'), (b'dslam_ping_error', b'DSLAM Ping Error'), (b'dslam_trace_route_error', b'DSLAM Trace Route Error')], default=b'dslam_connection_error', max_length=100),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_attainable_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='downstream_tx_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_attainable_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='upstream_tx_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
