# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0074_auto_20161015_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='access_name',
            field=models.CharField(blank=True, default=b'new', max_length=256, null=True, verbose_name='Access Name (vendor: FiberHome)'),
        ),
    ]
