# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0082_city_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMPortMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DSLAMPortVlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dslamport',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='dslamport',
            name='vlan',
        ),
        migrations.AddField(
            model_name='dslamportvlan',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAMPort'),
        ),
        migrations.AddField(
            model_name='dslamportvlan',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dslam.Vlan'),
        ),
        migrations.AddField(
            model_name='dslamportmac',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAMPort'),
        ),
    ]
