# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0084_dslamportvlan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='code',
            field=models.CharField(default='1234', max_length=256),
            preserve_default=False,
        ),
    ]
