# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0087_auto_20161102_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellervlan',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='resellervlan',
            name='vlan',
        ),
        migrations.AddField(
            model_name='vlan',
            name='reseller',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dslam.Reseller'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set([('vid', 'vname', 'reseller')]),
        ),
        migrations.DeleteModel(
            name='ResellerVlan',
        ),
    ]
