# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0091_dslambulkcommandresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='show_command',
            field=models.BooleanField(default=False, verbose_name='Show command in port table'),
        ),
    ]
