# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0098_auto_20161203_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portcommand',
            name='cart_ports',
        ),
    ]
