# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 05:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0099_remove_portcommand_cart_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='portcommand',
            name='cart_ports',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
