# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0100_portcommand_cart_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamport',
            name='downstream_attainable_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='upstream_attainable_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
