# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0103_auto_20161205_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomCenterMDFConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dslamport',
            name='line_profile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
