# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0106_auto_20161213_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerport',
            name='identifier_key',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='customerport',
            name='username',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
