# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0110_command_command_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_template',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
