# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0113_auto_20170114_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamport',
            name='selt_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
