# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0118_dslamboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamboard',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
