# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0120_dslamboard_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslamboard',
            name='hw_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
