# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0121_dslamboard_hw_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dslamboard',
            options={'ordering': ('cart_number',)},
        ),
        migrations.AddField(
            model_name='dslam',
            name='hostname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
