# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0122_auto_20170128_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dslamboard',
            options={'ordering': ('card_number',)},
        ),
        migrations.RenameField(
            model_name='dslamboard',
            old_name='cart_number',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='dslamboard',
            old_name='cart_type',
            new_name='card_type',
        ),
    ]
