# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0130_auto_20170225_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DSLAMWastedConfig',
            new_name='DSLAMFaultyConfig',
        ),
        migrations.RenameModel(
            old_name='DSLAMPortWested',
            new_name='DSLAMPortFaulty',
        ),
    ]
