# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0131_auto_20170225_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lineprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='dslam',
        ),
    ]
