# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0134_auto_20170301_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerport',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customerport',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
