# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0135_auto_20170301_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dslamstatus',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='dslamstatussnapshot',
            name='uptime',
        ),
    ]
