# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0136_auto_20170303_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='dslam_type',
            field=models.ManyToManyField(to='dslam.DSLAMType'),
        ),
    ]
