# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0137_command_dslam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMTypeCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_template', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='command',
            name='dslam_type',
        ),
        migrations.AddField(
            model_name='dslamtypecommand',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.Command'),
        ),
        migrations.AddField(
            model_name='dslamtypecommand',
            name='dslam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAMType'),
        ),
    ]
