# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0139_auto_20170305_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dslamcommand',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='portcommand',
            options={'ordering': ('created_at',)},
        ),
    ]
