# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0141_remove_command_command_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dslamcommand',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='portcommand',
            options={'ordering': ('-created_at',)},
        ),
    ]
