# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0142_auto_20170307_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
