# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 07:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0143_auto_20170311_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineprofile',
            name='ds_transmit_rate_adaptation',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='max_ds_snr_margin',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='max_us_snr_margin',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='min_ds_snr_margin',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='min_us_snr_margin',
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='extra_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=2048, null=True),
        ),
    ]
