# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0144_auto_20170312_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProfileExtraSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=256)),
                ('attr_value', models.CharField(max_length=256)),
                ('line_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.LineProfile')),
            ],
        ),
    ]
