# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0145_lineprofileextrasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineprofile',
            name='extra_settings',
        ),
    ]
