# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0146_remove_lineprofile_extra_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfdslam',
            name='status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'FAULTY', b'Faulty'), (b'DELEGATE', b'Delegate')], default=b'disable', max_length=50),
        ),
        migrations.AlterField(
            model_name='telecomcentermdfconfig',
            name='status_of_port',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'FAULTY', b'Faulty'), (b'DELEGATE', b'Delegate')], default=b'DISABLE', max_length=8),
        ),
    ]
