# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0154_auto_20170315_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslamportsnapshot',
            name='snp_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
