# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0157_dslamportfaulty_dslam_faulty_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
