# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0160_dslam_fqdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='channel_mode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='template_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
