# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0161_auto_20170506_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='dslam_type',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
