# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0162_lineprofile_dslam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='english_name',
        ),
        migrations.AddField(
            model_name='city',
            name='abbr',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
