# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0164_city_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='english_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
