# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0165_telecomcenter_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcenter',
            name='english_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
