# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0167_auto_20170606_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcentermdf',
            name='floor_counting_status',
            field=models.CharField(choices=[(b'ODD', b'odd'), (b'EVEN', b'even'), (b'STANDARD', b'standard')], default=b'STANDARD', max_length=8),
        ),
        migrations.AddField(
            model_name='telecomcentermdf',
            name='port_start',
            field=models.IntegerField(default=1),
        ),
    ]
