# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0168_auto_20170607_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='port_start',
            new_name='connection_start',
        ),
    ]
