# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0172_auto_20170607_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telecomcentermdfconfig',
            name='telecom_center_mdf',
        ),
        migrations.AddField(
            model_name='telecomcentermdf',
            name='port_counting_status',
            field=models.CharField(choices=[(b'ODD', b'odd'), (b'EVEN', b'even'), (b'STANDARD', b'standard')], default=b'STANDARD', max_length=8),
        ),
        migrations.AddField(
            model_name='telecomcentermdf',
            name='status_of_port',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'BUSY', b'Busy'), (b'DISABLE', b'Disable'), (b'VPN', b'VPN'), (b'FAULTY', b'Faulty'), (b'RESELLER', b'Reseller')], default=b'FREE', max_length=8),
        ),
        migrations.DeleteModel(
            name='TelecomCenterMDFConfig',
        ),
    ]
