# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0173_auto_20170607_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSLAMCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('cart_count', models.IntegerField()),
                ('cart_start', models.IntegerField()),
                ('port_count', models.IntegerField()),
                ('port_start', models.IntegerField()),
                ('dslam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.DSLAM')),
            ],
        ),
        migrations.RenameField(
            model_name='telecomcentermdf',
            old_name='port_counting_status',
            new_name='connection_counting_status',
        ),
    ]
