# Generated by Django 3.1.2 on 2020-12-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0179_auto_20201206_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
