# Generated by Django 3.1.2 on 2020-12-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0182_equipmentcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
        migrations.DeleteModel(
            name='EquipmentlinksInfo',
        ),
        migrations.DeleteModel(
            name='TelecomContractType',
        ),
    ]
