# Generated by Django 3.1.2 on 2020-12-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0185_auto_20201207_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_card_status_description', models.CharField(max_length=1000)),
                ('port_rental_invoice_description', models.CharField(max_length=1000)),
                ('assigned_gateways', models.IntegerField(blank=True, default=0, null=True)),
                ('total_active_ports', models.IntegerField(blank=True, default=0, null=True)),
                ('active_ports_assigned_percentage', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TelecomContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentlinksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.city')),
                ('dslam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.dslamtype')),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.equipmentcategory')),
                ('telecom_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter')),
                ('telecom_center_contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcontracttype')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='equipment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.equipmentcategorytype'),
        ),
    ]
