# Generated by Django 3.1.2 on 2020-12-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0189_auto_20201207_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_card_status_description', models.CharField(max_length=1000)),
                ('port_rental_invoice_description', models.CharField(max_length=1000)),
                ('assigned_gateways', models.IntegerField(blank=True, default=0, null=True)),
                ('total_active_ports', models.IntegerField(blank=True, default=0, null=True)),
                ('active_ports_assigned_percentage', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TelecomContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PowerEquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routers_switches_converters_consumption', models.IntegerField(blank=True, default=0, null=True)),
                ('server_cache_ventilation_fan_consumption', models.IntegerField(blank=True, default=0, null=True)),
                ('dc_amperage_consumption', models.IntegerField(blank=True, default=0, null=True)),
                ('dc_fuse_approved', models.CharField(max_length=259)),
                ('dc_fuse_Invoiced', models.CharField(max_length=259)),
                ('dc_amperage_difference', models.CharField(max_length=259)),
                ('three_phase_ac_fuse_approved', models.CharField(max_length=259)),
                ('phase_ac_fuse_approved', models.CharField(max_length=259)),
                ('ac_fuse_Invoiced', models.CharField(max_length=259)),
                ('ac_amperage_difference', models.CharField(max_length=259)),
                ('ac_dc_converter', models.CharField(max_length=259)),
                ('amperage_status_description', models.CharField(max_length=1000)),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.equipmentcategorytype')),
            ],
        ),
        migrations.CreateModel(
            name='PassiveEquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive_description', models.CharField(max_length=1000)),
                ('passive_computing_port', models.IntegerField(blank=True, default=0, null=True)),
                ('declared_passive_port', models.IntegerField(blank=True, default=0, null=True)),
                ('passive_port_differences', models.IntegerField(blank=True, default=0, null=True)),
                ('MDF_terminals_number', models.IntegerField(blank=True, default=0, null=True)),
                ('pap_cruise_terminals_number', models.IntegerField(blank=True, default=0, null=True)),
                ('equipment_mount_location', models.CharField(max_length=259)),
                ('rack_space', models.CharField(max_length=259)),
                ('cooling_status', models.BooleanField(default=False)),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.equipmentcategorytype')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentlinksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=256)),
                ('active_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.activeequipmentcategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.city')),
                ('dslam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.dslamtype')),
                ('passive_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.passiveequipmentcategory')),
                ('power_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.powerequipmentcategory')),
                ('telecom_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcenter')),
                ('telecom_center_contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.telecomcontracttype')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('active_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.activeequipmentcategory')),
                ('passive_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.passiveequipmentcategory')),
                ('power_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.powerequipmentcategory')),
            ],
        ),
        migrations.AddField(
            model_name='activeequipmentcategory',
            name='equipment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dslam.equipmentcategorytype'),
        ),
    ]
