# Generated by Django 3.1.2 on 2020-12-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0195_auto_20201208_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='equipment_category_type',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='dslam_type',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='telecom_center',
        ),
        migrations.RemoveField(
            model_name='equipmentlinksinfo',
            name='telecom_center_contract_type',
        ),
        migrations.RemoveField(
            model_name='passiveequipmentcategory',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='passiveequipmentcategory',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='powerequipmentcategory',
            name='equipment_category',
        ),
        migrations.DeleteModel(
            name='ActiveEquipmentCategory',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
        migrations.DeleteModel(
            name='EquipmentCategoryType',
        ),
        migrations.DeleteModel(
            name='EquipmentlinksInfo',
        ),
        migrations.DeleteModel(
            name='PassiveEquipmentCategory',
        ),
        migrations.DeleteModel(
            name='PowerEquipmentCategory',
        ),
        migrations.DeleteModel(
            name='TelecomContractType',
        ),
    ]
