# Generated by Django 3.2.5 on 2021-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0198_location_locationtype_router_routerbrand_routertype_switch_switchbrand_switchtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=250)),
                ('city_name', models.CharField(max_length=250)),
                ('telecom_name', models.CharField(max_length=250)),
                ('dslam_number', models.IntegerField()),
                ('card', models.IntegerField(blank=True, max_length=4, null=True)),
                ('portman_core', models.IntegerField(blank=True, max_length=4, null=True)),
                ('telco_row', models.IntegerField(blank=True, max_length=4, null=True)),
                ('telco_column', models.IntegerField(blank=True, max_length=4, null=True)),
                ('telco_connection', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
