# Generated by Django 3.2.5 on 2021-09-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0202_auto_20210922_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
