# Generated by Django 3.2.5 on 2021-09-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0204_testmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='Test_2Model',
        ),
    ]
