# Generated by Django 3.2.5 on 2021-10-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0201_auto_20210915_1225'),
        ('dslam', '0207_testmodel'),
    ]

    operations = [
    ]
