# Generated by Django 3.2.8 on 2022-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0213_portmanzabbixhosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='partak_telecom_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='telecomcenter',
            name='partak_telecom_name',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
