# Generated by Django 3.2.8 on 2022-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0214_auto_20220110_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcenter',
            name='partak_telecom_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
