# Generated by Django 3.2.8 on 2022-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0215_alter_telecomcenter_partak_telecom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='pishgaman_vci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dslam',
            name='pishgaman_vlan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dslam',
            name='pishgaman_vpi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
