# Generated by Django 3.2.8 on 2023-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0216_auto_20220514_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='long',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
