# Generated by Django 3.2.8 on 2023-07-31 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0218_city_sharepoint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dslam',
            name='last_backup_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 7, 31), null=True),
        ),
    ]
