# Generated by Django 3.2.8 on 2023-09-25 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0219_dslam_last_backup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dslam',
            name='last_backup_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 9, 25), null=True),
        ),
    ]
