# Generated by Django 3.2.8 on 2023-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dslam', '0221_alter_dslam_last_backup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcenter',
            name='lat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telecomcenter',
            name='long',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
