# Generated by Django 3.2.8 on 2025-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngn', '0002_advertiser_chakavak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedlist',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='MobileNumber',
        ),
    ]
