# Generated by Django 3.2.8 on 2025-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngn', '0004_blockedlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedlist',
            name='ibs_err',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
