# Generated by Django 3.2.8 on 2025-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngn', '0005_blockedlist_ibs_err'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedlist',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
